name: Run Stock Screener

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
  push:
    branches:
      - main

jobs:
  stock-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance

      - name: Run Python script
        run: |
          python fetch_data.py

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add stock_data.json
          git commit -m "Update stock data"
          git push
